### ISSUE TITLE
Pokémon Display Screen - loading animation

### ISSUE THREAD

**Issue by juanmanueldaza** [juanmanueldaza/pokedex#14]
- It should have some loading animation every time you load the site.

**Comment by JumaCodes** [comment]
I would love to work on this and resolve the issue.

**Comment by juanmanueldaza** [comment]
> I would love to work on this and resolve the issue.

@JumaCodes: Go for it! 

This is our first time working open sourced! We need help, time, and guidance to fully understand the proper use of Github Issues, Forks, and Pull requests.

If you are ok with it, you are welcome to contribute!
