### ISSUE TITLE
Display current pokémon stats on secondary screen

### ISSUE THREAD

**Issue by opablon** [juanmanueldaza/pokedex#31]
**Is your feature request related to a problem? Please describe.**
Show pokémon stats on secondary screen.

**Describe the solution you'd like**
Display HP, attack, defense and speed stats on secondary screen.

**Describe alternatives you've considered**
Display HP, attack, defense and speed stats on secondary screen.

**Additional context**

**Comment by juanmanueldaza** [comment]
The backward and forward buttons of the right side should iterate over different stats and display them on the big black screen also on the right side.
