### ISSUE TITLE
Que esté apretado el botón celeste que se muestra en pantalla negra

### ISSUE THREAD

**Issue by juanmanueldaza** [juanmanueldaza/pokedex#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by juanmanueldaza** [comment]
que sea tipo casetera vieja

**Comment by opablon** [comment]
fixed on comiit 25805a3d1e2703e8e40afc69d5ccff642475598c
