### ISSUE TITLE
botones que faltan: ayuda, búsqueda, reset

### ISSUE THREAD

**Issue by juanmanueldaza** [juanmanueldaza/pokedex#50]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/61162223/186540076-622d24ee-f330-456d-b8e0-9da51e5218dc.png)
ayuda busqueda reset

**Comment by juanmanueldaza** [comment]
el botón celeste de ayuda tiene que tener un signo de pregunta

**Comment by juanmanueldaza** [comment]
comportamiento botón de ayuda: cuando lo clickeás, no anda ningún otro botón, se cancelan todos los demás hovers.

el cursor se convierte en una lupa grande y cuando lo pasás por encima de las diferentes áreas de la Pokedex, muestra por pantala su función.

**Comment by opablon** [comment]
el botón reset se comporta como un F5 en el navegador

**Comment by opablon** [comment]
Done
